"""init migrations

Revision ID: 31672366557d
Revises: 
Create Date: 2025-09-12 17:47:43.740935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31672366557d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scorm_version', sa.String(), nullable=True),
    sa.Column('package_path', sa.String(), nullable=False),
    sa.Column('manifest_path', sa.String(), nullable=False),
    sa.Column('launch_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
