from app.models.state_ut import State_UT
from app.models.district import District
from app.models.block import Block
from app.models.activity_log import ActivityLog
from app.models.user import User
from app.models.courses import Course
from app.models.user_courses import UserCourse
from app.models.enrollments import Enrollment
from app.models.scorm_data import ScormData
from app.models.statements import Statement
from app.models.activities import Activity
from app.models.agents import Agent
from app.models.role import Role
from app.models.menu_item import MenuItem
from app.models.user_in_role import UserInRole
from app.models.menu_in_role import MenuInRole